class HueApi:
    def __init__(self, http: HttpClient):
        self.http = http

    # Light
    def list_lights(self) -> dict:
        ...
    def get_light(self, light_id: str) -> dict:
        ...
    def put_light(self, light_id: str, payload: dict) -> dict:
        ...

    # Group
    def list_groups(self) -> dict:
        ...
    def get_group(self, group_id: str) -> dict:
        ...
    def put_group(self, group_id: str, payload: dict) -> dict:
        ...

    # Room
    def list_rooms(self) -> dict:
        ...
    def get_room(self, room_id: str) -> dict:
        ...

    # Device
    def list_devices(self) -> dict:
        ...
    def get_device(self, device_id: str) -> dict:
        ...

    # Entertainment
    def list_entertainment(self) -> dict:
        ...
    def put_entertainment(self, ent_id: str, payload: dict) -> dict:
        ...